# 站点基本信息
title: 乐为舟的博客
email: your-email@example.com
description: "极简风格的个人博客"
baseurl: "" 
url: "https://xmleweizhou.github.io" # 替换为你的实际 URL

# 关键：显示未来日期的文章
future: true
timezone: Asia/Shanghai # 指定时区，避免日期解析错误

# Jekyll 配置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 博文相关配置
permalink: /posts/:title/
excerpt_separator: "<!-- more -->"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
