# 站点基本信息
#title: 乐为舟          # 例如：张三的技术博客
#email: your-email@example.com # 你的邮箱
#description: >-              # 博客描述
  
baseurl: ""                  # 留空即可（因为是根域名）
url: "https://xmleweizhou.github.io" # 你的博客地址
github_username: xmleweizhou # 例如：octocat

# 主题设置（使用GitHub官方推荐的minima主题）
theme: minima
plugins:
  - jekyll-feed              # 生成RSS订阅
  - jekyll-seo-tag
# 其他配置
markdown: kramdown
permalink: /:year/:month/:day/:title/
excerpt_separator: "<!-- more -->" # 手动指定摘要分隔符

# 排除的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
